### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [Gabriella439/bench#48]
👋 it has been five years since last release, thus, requesting a new one. Thanks!

**Comment by Gabriella439** [comment]
The reason I haven't cut a new release is because nothing actually changed since then other than dependency bounds (which I've already published as matching revisions to Hackage).  However, I can still cut a release if you want (especially if there was something I missed)

**Comment by chenrui333** [comment]
@Gabriella439 that would be great, I need a new release to get some build patch. Thanks!
